version: '3.8'

services:
  nginx:
      container_name: nginx
      # image: nginx:1.0.0
      build: ./requirements/nginx
      depends_on:
        - wordpress
      ports:
        - 443:443
      volumes:
        - wordpress_data:/var/www/html
      restart: always
      networks:
        - network

  mariadb:
    container_name: mariadb
    # image: mariadb:1.0.0
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    secrets:
      - db_root_password
      - db_password
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    # image: wordpress:1.0.0
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    secrets:
      - credentials
      - db_password
      - user_credentials

      
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hkizrak-/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hkizrak-/data/wordpress
      o: bind
      
networks:
  network:
    driver: bridge

secrets:
  user_credentials:
    file: ../secrets/user_credentials.txt
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
